version: '3.3'

services: 
    web:
      container_name: reactapp
      build:
        context: .
        dockerfile: Dockerfile
      volumes: 
        - '.:/app'
        - '/app/node_modules'
      ports: 
        - "3000:3000"
      environment:
        - NODE_ENV=development